### ISSUE TITLE
data generation

### ISSUE THREAD

**Issue by finger-monkey** [anthonyzhou-1/mae-pdes#1]
Hi, I am a novice in this field. Could you please provide more detailed experimental guidance? For example, I am very interested in the relevant parts of ResNet, but I am encountering some problems with data generation.

**Comment by anthonyzhou-1** [comment]
Sure thing, what parts of the data generation would you need help with? It could also be helpful to download data from the other repos used for this paper or use the some of the provided validation datasets [here](https://github.com/anthonyzhou-1/mae-pdes/tree/main/data_gen/data). Although it's only a few samples it could help to get your pipeline up and running. The ResNet architecture is from [ESRGAN](https://github.com/xinntao/ESRGAN/blob/master/RRDBNet_arch.py), but for a more PDE specific one, you can also refer to [PDEArena](https://github.com/pdearena/pdearena/blob/main/pdearena/modules/twod_resnet.py).
